spring:
  application:
    name: disboot-web
  profiles:
    active: @spring.profiles.active@
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/

dubbo:
  application:
    id: disboot-web
    name: disboot-web
    logger: slf4j
    qos-enable: true
    qos-port: 22223
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  ## RegistryConfig Bean
  registry:
    id: zk
    address: zookeeper://127.0.0.1:2181
    client: curator


server:
  servlet:
    context-path: /
  port: 8080
  tomcat:
    max-connections: 10000
