spring:
  application:
    name: disboot-biz
  main:
    web-application-type: NONE
  profiles:
    active: @spring.profiles.active@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.1.1.71:3306/test?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: paomiantv
    password: Paomiantv1&
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 3000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 1800000
      idle-timeout: 600000

mybatis:
  typeAliasesPackage: me.j360.disboot.mapper
  mapper-locations: classpath*:me/j360/disboot/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Dubbo Config properties
## ApplicationConfig Bean
dubbo:
  scan:
    basePackages: me.j360.disboot.service
  application:
    id: disboot-biz
    name: disboot-biz
    qos:
      port: 26001
      enable: true
  ## Enable multiple config bindings
  config:
    multiple: true
  ## ProtocolConfig Bean
  protocols:
    dubbo:
      name: dubbo
      port: 20880
      status: server
  ## RegistryConfig Bean
  registry:
    id: zk
    address: zookeeper://127.0.0.1:2181
    client: curator