spring:
  main:
    web-application-type: NONE
  profiles:
    active: @spring.profiles.active@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.1.1.71:3306/test?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: paomiantv
    password: Paomiantv1&
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 3000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 1800000
      idle-timeout: 600000

mybatis:
  typeAliasesPackage: me.j360.disboot.mapper
  mapper-locations: **.mapper
  configuration:
    map-underscore-to-camel-case: true


# Dubbo Config properties
## ApplicationConfig Bean
dubbo:
  scan:
    base-packages: me.j360.disboot.service
  application:
    qos:
      port: 0
      enable: true
  ## Enable multiple config bindings
  config:
    multiple: true
  ## ProtocolConfig Bean
  protocols:
    dubbo:
      name: dubbo
      port: 12345
      status: server
    rest:
      name: rest
      port: 8888
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: N/A